Feat/typescript
qquentinv/TheGoodBot pull request #18
Opened 2024-09-12 20:40 UTC by qquentinv

- use experimental node ts
- change all files in dot ts
- add types streamer

Close #11

2024-09-13 06:53 UTC, Yovach requested changes

2024-09-13 06:53 UTC, Yovach commented on src/api/twitchApi.ts
> +  const responseData: any = await rawResponse.json();
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/api/twitchApi.ts
> +  const response: any = await rawResponse.json();
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/api/twitchApi.ts
> +  streamStatus: any,
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/commands/add.ts
> +export function addCommand(client: Client, stdin: any[]) {
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/commands/delete.ts
> +export function deleteCommand(client: Client, stdin: any[]) {
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/commands/laststream.ts
> +export function laststreamCommand(client: Client, stdin: any[]) {
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/messages/categoryChanged.ts
> +  streamStatus: any,
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/messages/categoryChanged.ts
> +    (ch): ch is TextChannel => (ch as TextChannel).name === streamChannelName,
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/launchStream.ts
> +  streamStatus: any,
éviter l'utilisation du `any`

2024-09-13 06:53 UTC, Yovach commented on src/messages/launchStream.ts
> +    (ch): ch is TextChannel => (ch as TextChannel).name === streamChannelName,
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/reminderStream.ts
> +    (ch): ch is TextChannel => (ch as TextChannel).name === config.streamChannelName,
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/streamers.ts
> +    let formatedDate = new Date(date).toLocaleDateString("fr-FR");
utiliser le "const" car la variable n'est pas redéclarée

2024-09-13 06:53 UTC, Yovach commented on src/messages/utils.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/messages/utils.ts
> +    (ch): ch is TextChannel =>
Il n'y a pas de condition sur si le channel est de type TextChannel donc si un channel vocal a ce nom là, le typage est faux

2024-09-13 06:53 UTC, Yovach commented on src/services/generateDocx.ts
> +  const channelMessages: any = await msg.channel.messages
ne pas utiliser le "any"

2024-09-13 06:53 UTC, Yovach commented on src/services/generateDocx.ts
> +  await channelMessages.forEach((msg: { content: string; author: { bot: any; }; }) => {
ne pas utiliser le "any"

2024-09-19 20:08 UTC, qquentinv commented on src/api/twitchApi.ts
> +  streamStatus: any,
Que proposerais tu pour typer le streamStatus ?

2024-09-19 21:03 UTC, qquentinv commented on src/messages/utils.ts
> +    (ch): ch is TextChannel =>
Meme chose ici, je n'ai pas d'idée de comment faire

2024-09-21 08:10 UTC, Yovach commented on src/messages/utils.ts
> +    (ch): ch is TextChannel =>
Tu peux normalement faire quelque chose comme : 
```typescript
import type { Client, TextChannel } from "discord.js";
import { ChannelType } from "discord.js";

function getTextChannel(client: Client, name: string): TextChannel | undefined {
    return client.channels.cache.find((ch): ch is TextChannel => ch.type === ChannelType.GuildText && ch.name === name);
}

```

2024-09-21 12:05 UTC, merged